Force draft here cause it breaks site but why??
Error: Error building site: failed to render pages: open /opt/build/repo/public/blog/2019/10/03/how-to-prepare-for-a-bigger-than-normal-event/index.html: not a directory